### ISSUE TITLE
収集データのフィルタリング機能

### ISSUE THREAD

**Issue by nafuka11** [nafuka11/ft-progress-spreadsheet#5]
各Projectのデータを収集する際、user idでフィルタリングをかけます。

## 目的
- ダミーuserのデータを除外するため。
- データ収集を望まないuserに対応するため。

## 実装案
- フィルタリングするuser idのシートを作成します（シート名例：filterUser）。
- シートからidを取得し、fetchProjectInfo でidが一致するならcontinueします。

## その他
- sheet.writeProgress()から42 APIにアクセスするの、責務が分離できていない感じがするので、main.ts側からprojectInfosを渡してもいいかもしれません。

**Comment by nafuka11** [comment]
## TODO
- [ ] filterしたいuserのidを列挙しておく
- [ ] spreadsheet: filterUserシートを作成する。列挙したidを記載する
- [ ] sheet.ts: filterUserからuser idのリストを取得する
  - ~~fetchProjectIdsとやってることは同じなので、同じ関数にまとめる~~
    -> 今は同じにできるのですが、後々projectシートからはidとslugを取ってくる予定なので、分けたままでもいいかもしれません。
  - user idのリストはloggingする。その時どのidをfilterしたかはその時しか分からないため。
- [ ] ft.ts: fetchProjectInfo() でuser idのリストを元にデータをincrementするか判定する。
